"""
figure2-c reproducible version: Beijing thermal discomfort overlay with Weibo validation.

Reads pre-aggregated 750m grid GeoJSON (generated by figure2-c_export_grid.py)
instead of private building SHP data. Place the grid data folder alongside this script.

Expected directory structure:
    figure2c_grid_data/
    ├── Beijing_grid_heat.geojson
    ├── Beijing_basemap.geojson
    ├── Beijing_weibo_points.csv
    └── metadata.json
"""

import os, json, warnings
import numpy as np
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.cm import ScalarMappable
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches
from shapely.geometry import Point

warnings.filterwarnings("ignore")

# ==================== Configuration ====================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GRID_DATA_DIR = os.path.join(SCRIPT_DIR, "figure2c_grid_data")
OUTPUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "figure2c_output")

# ---- Plotting params (matching original figure2-c.py) ----
FIG_SIZE = (15, 15)
DPI = 600
MAIN_TO_MARGIN_RATIO = 9

MAP_BG_COLOR = '#F7F7F7'
MAP_EDGE_COLOR = '#D0D0D0'
MAP_EDGE_WIDTH = 0.8

SIM_CMAP_COLORS = ["#F7F4C3", "#931832"]
SIM_ALPHA = 0.85

WEIBO_COLOR = '#475894'
WEIBO_SIZE = 18
WEIBO_ALPHA = 0.9
WEIBO_EDGE_COLOR = 'white'
WEIBO_EDGE_WIDTH = 0.2

STAR_COLOR = '#FF0000'
STAR_SIZE = 1200

KDE_SIM_COLOR = '#931832'
KDE_SIM_ALPHA = 0.2
KDE_WEIBO_COLOR = '#475894'
KDE_WEIBO_ALPHA = 0.2


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ---- Load grid data ----
    grid_path = os.path.join(GRID_DATA_DIR, "Beijing_grid_heat.geojson")
    basemap_path = os.path.join(GRID_DATA_DIR, "Beijing_basemap.geojson")
    weibo_path = os.path.join(GRID_DATA_DIR, "Beijing_weibo_points.csv")
    meta_path = os.path.join(GRID_DATA_DIR, "metadata.json")

    for p in [grid_path, basemap_path, weibo_path, meta_path]:
        if not os.path.exists(p):
            raise FileNotFoundError(f"Missing grid data: {p}")

    print("Loading grid data...")
    grid_merged = gpd.read_file(grid_path)
    beijing_base = gpd.read_file(basemap_path)
    df_weibo = pd.read_csv(weibo_path, encoding='utf-8-sig')
    with open(meta_path, 'r', encoding='utf-8') as f:
        metadata = json.load(f)

    # ---- Restore derived arrays from grid data ----
    sim_grids = grid_merged[grid_merged['sim_risk'] > 0].copy()
    xlims = tuple(metadata['xlims_3857'])
    ylims = tuple(metadata['ylims_3857'])

    # Weibo point arrays
    weibo_x = df_weibo['x'].values
    weibo_y = df_weibo['y'].values

    # Sim centroid arrays (for KDE margin plots)
    sim_centroids = sim_grids.geometry.centroid
    sim_x = sim_centroids.x.values
    sim_y = sim_centroids.y.values
    sim_weights = sim_grids['sim_risk'].values

    # ---- Build colormap ----
    sim_cmap = LinearSegmentedColormap.from_list("sim_custom", SIM_CMAP_COLORS)

    # ==================== Plot ====================
    print("Rendering figure...")
    fig = plt.figure(figsize=FIG_SIZE, dpi=DPI, facecolor='none')

    gs = GridSpec(2, 2,
                  width_ratios=[MAIN_TO_MARGIN_RATIO, 1],
                  height_ratios=[1, MAIN_TO_MARGIN_RATIO],
                  wspace=0.03, hspace=0.03)

    # ---- Top margin KDE ----
    ax_top = fig.add_subplot(gs[0, 0])
    ax_top.patch.set_facecolor('none')
    sns.kdeplot(x=sim_x, weights=sim_weights, ax=ax_top, fill=True,
                color=KDE_SIM_COLOR, alpha=KDE_SIM_ALPHA, linewidth=0, cut=0)
    sns.kdeplot(x=weibo_x, ax=ax_top, fill=True,
                color=KDE_WEIBO_COLOR, alpha=KDE_WEIBO_ALPHA, linewidth=0, cut=0)
    ax_top.set_xlim(xlims)
    ax_top.axis('off')

    # ---- Right margin KDE ----
    ax_right = fig.add_subplot(gs[1, 1])
    ax_right.patch.set_facecolor('none')
    sns.kdeplot(y=sim_y, weights=sim_weights, ax=ax_right, fill=True,
                color=KDE_SIM_COLOR, alpha=KDE_SIM_ALPHA, linewidth=0, cut=0)
    sns.kdeplot(y=weibo_y, ax=ax_right, fill=True,
                color=KDE_WEIBO_COLOR, alpha=KDE_WEIBO_ALPHA, linewidth=0, cut=0)
    ax_right.set_ylim(ylims)
    ax_right.axis('off')

    # ---- Main map ----
    ax_main = fig.add_subplot(gs[1, 0])
    ax_main.patch.set_facecolor('none')
    ax_main.spines['top'].set_visible(False)
    ax_main.spines['right'].set_visible(False)
    ax_main.grid(True, linestyle='--', color='gray', alpha=0.5, zorder=0)

    # Basemap
    beijing_base.plot(ax=ax_main, facecolor=MAP_BG_COLOR, edgecolor=MAP_EDGE_COLOR,
                      linewidth=MAP_EDGE_WIDTH, zorder=1)
    # Simulation grid heat
    sim_grids.plot(ax=ax_main, column='sim_risk', cmap=sim_cmap,
                   edgecolor='none', alpha=SIM_ALPHA, zorder=2)
    # Weibo scatter
    ax_main.scatter(weibo_x, weibo_y, s=WEIBO_SIZE, c=WEIBO_COLOR, alpha=WEIBO_ALPHA,
                    edgecolor=WEIBO_EDGE_COLOR, linewidth=WEIBO_EDGE_WIDTH, zorder=3)
    # City center star
    star = gpd.GeoSeries(
        [Point(metadata['city_center_lon'], metadata['city_center_lat'])],
        crs="EPSG:4326"
    ).to_crs("EPSG:3857")[0]
    ax_main.scatter(star.x, star.y, marker='*', color=STAR_COLOR,
                    edgecolor='white', s=STAR_SIZE, zorder=10)

    ax_main.set_xlim(xlims)
    ax_main.set_ylim(ylims)

    save_path = os.path.join(OUTPUT_DIR, "Beijing_Overlay_Final_Grid.svg")
    fig.savefig(save_path, format='svg', dpi=DPI, bbox_inches='tight', transparent=True)
    plt.close(fig)
    print(f"[OK] Main figure: {save_path}")

    # ==================== Standalone legend ====================
    print("Generating legend...")
    vmin, vmax = sim_weights.min(), sim_weights.max()

    fig_leg = plt.figure(figsize=(6.5, 3), dpi=DPI, facecolor='none')
    gs_leg = GridSpec(1, 2, width_ratios=[1.5, 1], wspace=0.1)

    # Discrete legend (left)
    ax_leg_d = fig_leg.add_subplot(gs_leg[0])
    ax_leg_d.axis('off')
    legend_elements = [
        Line2D([0], [0], marker='o', color='none', label='Weibo Check-ins',
               markerfacecolor=WEIBO_COLOR, markersize=8,
               markeredgewidth=WEIBO_EDGE_WIDTH, markeredgecolor='white'),
        mpatches.Patch(color=KDE_SIM_COLOR, alpha=KDE_SIM_ALPHA,
                       label='Simulation Density (KDE)'),
        mpatches.Patch(color=KDE_WEIBO_COLOR, alpha=KDE_WEIBO_ALPHA,
                       label='Weibo Density (KDE)'),
        Line2D([0], [0], marker='*', color='none', label='City Center',
               markerfacecolor=STAR_COLOR, markersize=15)
    ]
    ax_leg_d.legend(handles=legend_elements, loc='center', frameon=False,
                    prop={'family': 'sans-serif', 'size': 12})

    # Colorbar (right)
    ax_leg_c = fig_leg.add_subplot(gs_leg[1])
    norm = Normalize(vmin=vmin, vmax=vmax)
    sm = ScalarMappable(cmap=sim_cmap, norm=norm)
    sm.set_array([])
    cbar = fig_leg.colorbar(sm, cax=ax_leg_c, orientation='vertical', alpha=SIM_ALPHA)
    cbar.set_label('Simulated Thermal\nDiscomfort (Hours)', fontname='sans-serif',
                   fontsize=12, labelpad=10)
    cbar.outline.set_edgecolor('none')
    cbar.ax.tick_params(labelsize=10, length=4, color='gray')
    for l in cbar.ax.yaxis.get_ticklabels():
        l.set_family('sans-serif')

    leg_path = os.path.join(OUTPUT_DIR, "Legend_Standalone_WithCbar.svg")
    fig_leg.savefig(leg_path, format='svg', transparent=True, bbox_inches='tight')
    plt.close(fig_leg)
    print(f"[OK] Legend: {leg_path}")
    print(f"\n[OK] All outputs saved to: {OUTPUT_DIR}")


if __name__ == '__main__':
    main()
