"""
figure2-d reproducible version: 6-city 3D stacked heat discomfort maps.

Reads pre-aggregated grid GeoJSON files (generated by figure2-d_export_grid.py)
instead of private building SHP data. Place the grid data folder in the same
directory as this script, or edit GRID_DATA_DIR below.

Expected directory structure:
    figure2d_grid_data/
    └── <CityName>/
        ├── <City>_grid_heat.geojson
        ├── <City>_core_hull.geojson
        ├── <City>_core_counties.geojson
        ├── <City>_index_counties.geojson
        └── metadata.json
"""

import os, json, warnings
import numpy as np
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.font_manager as fm

import shapely.affinity
from shapely.geometry import Point

warnings.filterwarnings("ignore")

# ==================== Configuration ====================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GRID_DATA_DIR = os.path.join(SCRIPT_DIR, "figure2d_grid_data")
OUTPUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "figure2d_output")

CITY_EN_LIST = ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Wuhan", "Xiamen"]

CUSTOM_COLORS = ['#3850A1', '#7EA8C3', '#F7F4C3', '#EBB97F', '#D56B52', '#931832']
CUSTOM_LABELS = ['0 - 5', '5 - 15', '15 - 30', '30 - 70', '70 - 140', '>140']

SCENARIO_COLS = {
    '2020':            'HEAT_2020',
    '2040-rcp8.5':     'HEAT_2040_RCP85',
    '2060-rcp8.5':     'HEAT_2060_RCP85',
}
SCENARIO_TITLES = {
    '2020': '2020 Baseline',
    '2040-rcp8.5': '2040 RCP 8.5',
    '2060-rcp8.5': '2060 RCP 8.5',
}


def get_discrete_color(val):
    if pd.isna(val) or val <= 5:
        return CUSTOM_COLORS[0]
    elif val <= 15:
        return CUSTOM_COLORS[1]
    elif val <= 30:
        return CUSTOM_COLORS[2]
    elif val <= 70:
        return CUSTOM_COLORS[3]
    elif val <= 140:
        return CUSTOM_COLORS[4]
    else:
        return CUSTOM_COLORS[5]


# ==================== 3D transform ====================

def transform_to_3d_strict(geom, z_offset=0):
    if geom is None or geom.is_empty:
        return geom
    tilt_z_deg = 60
    rot_flat_deg = 0
    rx, rz = np.radians(tilt_z_deg), np.radians(rot_flat_deg)
    a, b = np.cos(rz), -np.sin(rz)
    d, e = np.sin(rz) * np.cos(rx), np.cos(rz) * np.cos(rx)
    xoff, yoff = 0, -z_offset
    return shapely.affinity.affine_transform(geom, [a, b, d, e, xoff, yoff])


def apply_3d_strict(gdf, z_offset=0):
    if gdf is None or gdf.empty:
        return gdf
    gdf_3d = gdf.copy()
    gdf_3d['geometry'] = gdf_3d.geometry.apply(
        lambda geom: transform_to_3d_strict(geom, z_offset))
    return gdf_3d


# ==================== Scalebar ====================

def add_scalebar(ax, lat):
    plt.draw()
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    total_map_units = xmax - xmin
    total_true_km = (total_map_units * np.cos(np.radians(lat))) / 1000.0
    target_km = total_true_km * 0.2

    if target_km <= 5:       length_km = 2
    elif target_km <= 15:    length_km = 5
    elif target_km <= 35:    length_km = 10
    elif target_km <= 75:    length_km = 20
    else:                    length_km = 50

    width_map_units = (length_km * 1000.0) / np.cos(np.radians(lat))
    x0 = xmin + (xmax - xmin) * 0.05
    y0 = ymin + (ymax - ymin) * 0.05
    tick_height = (ymax - ymin) * 0.015
    lw = 2
    z_layer = 100

    ax.plot([x0, x0 + width_map_units], [y0, y0], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0, x0], [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0 + width_map_units / 2, x0 + width_map_units / 2],
            [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0 + width_map_units, x0 + width_map_units],
            [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)

    font_prop = fm.FontProperties(size=14)
    ax.text(x0, y0 + tick_height * 1.5, '0', ha='center', va='bottom',
            color='black', fontproperties=font_prop, zorder=z_layer)
    ax.text(x0 + width_map_units, y0 + tick_height * 1.5, f'{length_km} km',
            ha='center', va='bottom', color='black', fontproperties=font_prop, zorder=z_layer)


# ==================== Load grid data ====================

def load_city_grid_data(grid_data_dir, city_en):
    """Load all GeoJSON layers + metadata for one city."""
    city_dir = os.path.join(grid_data_dir, city_en)

    # Grid heat data
    grid_path = os.path.join(city_dir, f"{city_en}_grid_heat.geojson")
    grid_core = gpd.read_file(grid_path)

    # Normalize column names (GeoJSON may rename them)
    col_map = {}
    for c in grid_core.columns:
        if '2020' in c and '2040' not in c and '2060' not in c:
            col_map[c] = 'HEAT_2020'
        elif '2040' in c or '2040-rcp8' in c:
            col_map[c] = 'HEAT_2040_RCP85'
        elif '2060' in c or '2060-rcp8' in c:
            col_map[c] = 'HEAT_2060_RCP85'
    grid_core = grid_core.rename(columns=col_map)

    # Core hull
    hull_path = os.path.join(city_dir, f"{city_en}_core_hull.geojson")
    core_hull = gpd.read_file(hull_path)

    # Core counties
    county_path = os.path.join(city_dir, f"{city_en}_core_counties.geojson")
    core_counties = gpd.read_file(county_path)

    # Index counties
    index_path = os.path.join(city_dir, f"{city_en}_index_counties.geojson")
    index_counties = gpd.read_file(index_path)

    # Metadata
    with open(os.path.join(city_dir, 'metadata.json'), 'r', encoding='utf-8') as f:
        metadata = json.load(f)

    return grid_core, core_hull, core_counties, index_counties, metadata


# ==================== City plot ====================

def plot_single_city(city_en, grid_core, core_hull, core_counties, index_counties, metadata):
    lat = metadata['city_center_lat']
    lon = metadata['city_center_lon']
    grid_sz = metadata['grid_size_m']

    # City center star
    star_point_3857 = gpd.GeoSeries(
        [Point(lon, lat)], crs="EPSG:4326").to_crs("EPSG:3857")[0]
    star_3d = transform_to_3d_strict(star_point_3857, z_offset=0)

    fig, axes = plt.subplots(1, 4, figsize=(28, 10),
                             gridspec_kw={'width_ratios': [1, 1, 1, 0.7]},
                             facecolor='none')
    fig.patch.set_alpha(0.0)
    plt.subplots_adjust(bottom=0.15, wspace=0.05)

    minx, miny, maxx, maxy = core_hull.total_bounds
    dynamic_thickness = (maxy - miny) * 0.03

    for i, (yr, col_name) in enumerate(SCENARIO_COLS.items()):
        ax = axes[i]
        ax.set_facecolor('none')
        ax.set_axis_off()

        # Shadow layers
        for z in np.linspace(dynamic_thickness, 0, 15):
            apply_3d_strict(core_hull, z_offset=z).plot(
                ax=ax, facecolor='#cccccc', edgecolor='none', zorder=1)

        # Top base plate
        hull_top = apply_3d_strict(core_hull, z_offset=0)
        hull_top.plot(ax=ax, facecolor='#F7F7F7', edgecolor='none', zorder=2)

        # Grid heat
        grid_core[f'color_{yr}'] = grid_core[col_name].apply(get_discrete_color)
        grid_3d = apply_3d_strict(grid_core, z_offset=0)
        grid_3d.plot(ax=ax, color=grid_3d[f'color_{yr}'], edgecolor='none', zorder=3)

        # Administrative boundaries
        apply_3d_strict(core_counties, z_offset=0).boundary.plot(
            ax=ax, color='#888888', linewidth=0.6, zorder=4)
        hull_top.boundary.plot(ax=ax, color='#666666', linewidth=1.2, zorder=5)

        # City center star
        ax.scatter(star_3d.x, star_3d.y, marker='*', color='red',
                   edgecolor='white', s=700, zorder=15, label="City Center")

        ax.set_title(f"{city_en}  {SCENARIO_TITLES[yr]}", fontsize=20,
                     pad=20, fontweight='bold')
        viz_bounds = hull_top.total_bounds
        ax.set_xlim(viz_bounds[0] - 5000, viz_bounds[2] + 5000)
        ax.set_ylim(viz_bounds[1] - 10000, viz_bounds[3] + 5000)

        add_scalebar(ax, lat)

    # Colorbar
    cmap_discrete = mcolors.ListedColormap(CUSTOM_COLORS)
    norm_discrete = mcolors.Normalize(vmin=0, vmax=len(CUSTOM_COLORS))
    sm = plt.cm.ScalarMappable(cmap=cmap_discrete, norm=norm_discrete)
    sm._A = []

    cbar_ax = fig.add_axes([0.25, 0.08, 0.4, 0.03])
    cbar = fig.colorbar(sm, cax=cbar_ax, orientation='horizontal')
    ticks_loc = np.arange(len(CUSTOM_COLORS)) + 0.5
    cbar.set_ticks(ticks_loc)
    cbar.set_ticklabels(CUSTOM_LABELS)
    cbar.ax.tick_params(labelsize=15, length=0)
    cbar.set_label('Per-Capita Discomfort Hours', fontsize=16, labelpad=10)

    # Index map
    ax_idx = axes[3]
    index_counties.plot(ax=ax_idx, color='#EEEEEE', edgecolor='#B0B0B0', linewidth=0.5)
    core_counties.plot(ax=ax_idx, color='#E67E22', alpha=0.8)
    core_counties.boundary.plot(ax=ax_idx, color='#C0392B', linewidth=0.5)
    core_hull.boundary.plot(ax=ax_idx, color='#D35400', linewidth=1.0)
    ax_idx.set_title("Index (Plan View)", fontsize=18)
    ax_idx.set_axis_off()

    save_path = os.path.join(OUTPUT_DIR, f"{city_en}_3D_Heat_Discrete_600dpi.png")
    fig.savefig(save_path, dpi=600, bbox_inches='tight', transparent=True)
    plt.close(fig)
    print(f"  [OK] {save_path}")


# ==================== Main ====================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for city_en in CITY_EN_LIST:
        city_dir = os.path.join(GRID_DATA_DIR, city_en)
        if not os.path.isdir(city_dir):
            print(f"  [SKIP] {city_en}: grid data not found at {city_dir}")
            continue
        print(f"\n>> Plotting: {city_en}")
        grid_core, core_hull, core_counties, index_counties, metadata = \
            load_city_grid_data(GRID_DATA_DIR, city_en)
        plot_single_city(city_en, grid_core, core_hull, core_counties,
                         index_counties, metadata)

    print(f"\n[OK] All figures saved to: {OUTPUT_DIR}")


if __name__ == '__main__':
    main()
