"""
figure5 reproducible version: 6-city 3D stacked bivariate maps (2x2 heat x vulnerability).

Reads pre-aggregated grid GeoJSON files (generated by figure5_export_grid.py)
instead of private building SHP data. Place the grid data folder in the same
directory as this script, or edit GRID_DATA_DIR below.

Expected directory structure:
    figure5_grid_data/
    └── <City>/
        ├── <City>_grid_bivariate.geojson
        ├── <City>_core_hull.geojson
        ├── <City>_core_counties.geojson
        ├── <City>_index_counties.geojson
        └── metadata.json
"""

import os, json, warnings
import numpy as np
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.font_manager as fm

import shapely.affinity
from shapely.geometry import Point

warnings.filterwarnings("ignore")

# ==================== Configuration ====================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GRID_DATA_DIR = os.path.join(SCRIPT_DIR, "figure5_grid_data")
OUTPUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "output/figure5")

CITY_EN_LIST = ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Wuhan", "Xiamen"]

# 2x2 bivariate color scheme: X=heat (Red), Y=vulnerability (Blue)
bivariate_colors_2x2 = {
    "1-1": "#CAE8F2",  # Low heat, low vulnerability
    "2-1": "#FDBA6D",  # High heat, low vulnerability
    "1-2": "#3A51A1",  # Low heat, high vulnerability
    "2-2": "#C81D31",  # High heat, high vulnerability
}

HEAT_LOWER_PERCENTILE = 0
HEAT_UPPER_PERCENTILE = 95
VUL_LOWER_PERCENTILE = 0
VUL_UPPER_PERCENTILE = 95


def get_class_2x2(val, mid_val):
    """2x2 binary classifier: <= midpoint = 1 (low), > midpoint = 2 (high)"""
    if pd.isna(val):
        return None
    return 1 if val <= mid_val else 2


# ==================== 3D transform ====================

def transform_to_3d_strict(geom, z_offset=0):
    if geom is None or geom.is_empty:
        return geom
    tilt_z_deg = 60
    rot_flat_deg = 0
    rx, rz = np.radians(tilt_z_deg), np.radians(rot_flat_deg)
    a, b = np.cos(rz), -np.sin(rz)
    d, e = np.sin(rz) * np.cos(rx), np.cos(rz) * np.cos(rx)
    xoff, yoff = 0, -z_offset
    return shapely.affinity.affine_transform(geom, [a, b, d, e, xoff, yoff])


def apply_3d_strict(gdf, z_offset=0):
    if gdf is None or gdf.empty:
        return gdf
    gdf_3d = gdf.copy()
    gdf_3d['geometry'] = gdf_3d.geometry.apply(
        lambda geom: transform_to_3d_strict(geom, z_offset))
    return gdf_3d


# ==================== Scalebar ====================

def add_scalebar(ax, lat):
    plt.draw()
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    total_map_units = xmax - xmin
    total_true_km = (total_map_units * np.cos(np.radians(lat))) / 1000.0
    target_km = total_true_km * 0.2

    if target_km <= 5:
        length_km = 2
    elif target_km <= 15:
        length_km = 5
    elif target_km <= 35:
        length_km = 10
    elif target_km <= 75:
        length_km = 20
    else:
        length_km = 50

    width_map_units = (length_km * 1000.0) / np.cos(np.radians(lat))
    x0 = xmin + (xmax - xmin) * 0.05
    y0 = ymin + (ymax - ymin) * 0.05
    tick_height = (ymax - ymin) * 0.015
    lw = 2
    z_layer = 100

    ax.plot([x0, x0 + width_map_units], [y0, y0], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0, x0], [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0 + width_map_units / 2, x0 + width_map_units / 2],
            [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)
    ax.plot([x0 + width_map_units, x0 + width_map_units],
            [y0, y0 + tick_height], color='black', lw=lw, zorder=z_layer)

    font_prop = fm.FontProperties(size=14)
    ax.text(x0, y0 + tick_height * 1.5, '0', ha='center', va='bottom',
            color='black', fontproperties=font_prop, zorder=z_layer)
    ax.text(x0 + width_map_units, y0 + tick_height * 1.5, f'{length_km} km',
            ha='center', va='bottom', color='black', fontproperties=font_prop, zorder=z_layer)


# ==================== Load grid data ====================

def load_city_grid_data(grid_data_dir, city_en):
    """Load all GeoJSON layers + metadata for one city."""
    city_dir = os.path.join(grid_data_dir, city_en)

    # Grid bivariate data (heat + vulnerability)
    grid_path = os.path.join(city_dir, f"{city_en}_grid_bivariate.geojson")
    grid_core = gpd.read_file(grid_path)

    # Normalize column names (GeoJSON may truncate/rename them)
    col_map = {}
    for c in grid_core.columns:
        if c == 'geometry':
            continue
        if '2020' in c and '2040' not in c and '2060' not in c:
            col_map[c] = 'HEAT_2020'
        elif '2040' in c:
            col_map[c] = 'HEAT_2040'
        elif '2060' in c:
            col_map[c] = 'HEAT_2060'
        elif 'Vuln' in c or 'vuln' in c:
            col_map[c] = 'VULNERABILITY'
    grid_core = grid_core.rename(columns=col_map)

    # Core hull
    hull_path = os.path.join(city_dir, f"{city_en}_core_hull.geojson")
    core_hull = gpd.read_file(hull_path)

    # Core counties
    county_path = os.path.join(city_dir, f"{city_en}_core_counties.geojson")
    core_counties = gpd.read_file(county_path)

    # Index counties
    index_path = os.path.join(city_dir, f"{city_en}_index_counties.geojson")
    index_counties = gpd.read_file(index_path)

    # Metadata
    with open(os.path.join(city_dir, 'metadata.json'), 'r', encoding='utf-8') as f:
        metadata = json.load(f)

    return grid_core, core_hull, core_counties, index_counties, metadata


# ==================== City plot ====================

def plot_single_city(city_en, grid_core, core_hull, core_counties,
                      index_counties, metadata):
    lat = metadata['city_center_lat']
    lon = metadata['city_center_lon']

    # Compute 2x2 thresholds
    all_heat = pd.concat([
        grid_core['HEAT_2020'], grid_core['HEAT_2040'], grid_core['HEAT_2060']
    ]).dropna()
    h_mid = (np.percentile(all_heat, HEAT_LOWER_PERCENTILE) +
             np.percentile(all_heat, HEAT_UPPER_PERCENTILE)) / 2
    vul_vals = grid_core['VULNERABILITY'].dropna()
    v_mid = (np.percentile(vul_vals, VUL_LOWER_PERCENTILE) +
             np.percentile(vul_vals, VUL_UPPER_PERCENTILE)) / 2

    # City center star
    star_point_3857 = gpd.GeoSeries(
        [Point(lon, lat)], crs="EPSG:4326").to_crs("EPSG:3857")[0]
    star_3d = transform_to_3d_strict(star_point_3857, z_offset=0)

    fig, axes = plt.subplots(1, 4, figsize=(28, 10),
                             gridspec_kw={'width_ratios': [1, 1, 1, 0.7]},
                             facecolor='none')
    fig.patch.set_alpha(0.0)
    plt.subplots_adjust(wspace=0.05)

    minx, miny, maxx, maxy = core_hull.total_bounds
    dynamic_thickness = (maxy - miny) * 0.03

    scenarios = [
        ('2020', 'HEAT_2020', '2020 Baseline'),
        ('2040-rcp8.5', 'HEAT_2040', '2040 RCP 8.5'),
        ('2060-rcp8.5', 'HEAT_2060', '2060 RCP 8.5'),
    ]

    for i, (yr, col_name, ttl) in enumerate(scenarios):
        ax = axes[i]
        ax.set_facecolor('none')
        ax.set_axis_off()

        # Shadow layers
        for z in np.linspace(dynamic_thickness, 0, 15):
            apply_3d_strict(core_hull, z_offset=z).plot(
                ax=ax, facecolor='#cccccc', edgecolor='none', zorder=1)

        # Top base plate
        hull_top = apply_3d_strict(core_hull, z_offset=0)
        hull_top.plot(ax=ax, facecolor='#F7F7F7', edgecolor='none', zorder=2)

        # 2x2 bivariate grid
        grid_core[f'clr_{yr}'] = grid_core.apply(
            lambda r: f"{get_class_2x2(r[col_name], h_mid)}-{get_class_2x2(r['VULNERABILITY'], v_mid)}",
            axis=1)
        grid_3d = apply_3d_strict(grid_core, z_offset=0)
        for c_class, hex_c in bivariate_colors_2x2.items():
            subset = grid_3d[grid_3d[f'clr_{yr}'] == c_class]
            if not subset.empty:
                subset.plot(ax=ax, color=hex_c, edgecolor='none', zorder=3)

        # Administrative boundaries
        apply_3d_strict(core_counties, z_offset=0).boundary.plot(
            ax=ax, color='#888888', linewidth=0.6, zorder=4)
        hull_top.boundary.plot(ax=ax, color='#666666', linewidth=1.2, zorder=5)

        # City center star
        ax.scatter(star_3d.x, star_3d.y, marker='*', color='red',
                   edgecolor='white', s=350, zorder=15, label="City Center")

        ax.set_title(f"{city_en}  {ttl}", fontsize=20, pad=20, fontweight='bold')
        viz_bounds = hull_top.total_bounds
        ax.set_xlim(viz_bounds[0] - 5000, viz_bounds[2] + 5000)
        ax.set_ylim(viz_bounds[1] - 10000, viz_bounds[3] + 5000)

        add_scalebar(ax, lat)

    # Index map
    ax_idx = axes[3]
    index_counties.plot(ax=ax_idx, color='#EEEEEE', edgecolor='#B0B0B0', linewidth=0.5)
    core_counties.plot(ax=ax_idx, color='#E67E22', alpha=0.8)
    core_counties.boundary.plot(ax=ax_idx, color='#C0392B', linewidth=0.5)
    core_hull.boundary.plot(ax=ax_idx, color='#D35400', linewidth=1.0)
    ax_idx.set_title("Index (Plan View)", fontsize=18)
    ax_idx.set_axis_off()

    save_path = os.path.join(OUTPUT_DIR, f"{city_en}_3D_Bivariate_600dpi.png")
    fig.savefig(save_path, dpi=600, bbox_inches='tight', transparent=True)
    plt.close(fig)
    print(f"  [OK] {save_path}")


# ==================== Main ====================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for city_en in CITY_EN_LIST:
        city_dir = os.path.join(GRID_DATA_DIR, city_en)
        if not os.path.isdir(city_dir):
            print(f"  [SKIP] {city_en}: grid data not found at {city_dir}")
            continue
        print(f"\n>> Plotting: {city_en}")
        grid_core, core_hull, core_counties, index_counties, metadata = \
            load_city_grid_data(GRID_DATA_DIR, city_en)
        plot_single_city(city_en, grid_core, core_hull, core_counties,
                         index_counties, metadata)

    print(f"\n[DONE] All figures saved to: {OUTPUT_DIR}")


if __name__ == '__main__':
    main()
